name: Development Workflow

on:
  pull_request:
    types: [edited, synchronize, opened, reopened]
    branches:
      - main

jobs:
  testing:
    name: test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        ports:
          - 5432:5432
        env:
            POSTGRES_USER: development
            POSTGRES_PASSWORD: development
            POSTGRES_DB: development
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.23.x
      - name: Set GOBIN
        run: go env -w GOBIN=/usr/local/bin
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          go mod download
          go install -mod=mod github.com/onsi/ginkgo/v2/ginkgo
      - name: Tests
        env:
          TEST_DB_DNS: postgres://development:development@localhost:5432/development?sslmode=disable
        run: make test
